server:
  port: 8080
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.29.222.57:3306/testSql?useUnicode=true&characterEncoding=utf8
      username: root
      password: dw123456


mybatis:
   mapperLocations: classpath:/mybatis/*.xml
